### ISSUE TITLE
Headcrab takeover animation glitch 

### ISSUE THREAD

**Issue by Em3rg3ncy** [Headcrabs-Plus/Headcrabs-plus-Github#13]
I'm having issues to play with the mod, having glitches during the takeover animation
![image](https://user-images.githubusercontent.com/43929581/46581887-f37d7200-ca71-11e8-89b2-ed7df8aefc81.png)
https://youtu.be/mEH1N49AFH0
There are also stutters during the animation

**Comment by rajawilliams** [comment]
Duplicate of #9

**Comment by rajawilliams** [comment]
Duplicate of #9
